services:
  postgres:
    image: postgres:16
    container_name: ePerencanaan-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ePerencanaan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ePerencanaan-network

  redis:
    image: redis:7
    container_name: ePerencanaan-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ePerencanaan-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ePerencanaan-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ePerencanaan-network

volumes:
  postgres_data:

networks:
  ePerencanaan-network:
