ALTER TABLE "kro" ALTER COLUMN "id" TYPE VARCHAR(20);
ALTER TABLE "ro" ALTER COLUMN "id" TYPE VARCHAR(20);
ALTER TABLE "ro" ALTER COLUMN "kroId" TYPE VARCHAR(20);
ALTER TABLE "indikator_ro" ALTER COLUMN "roId" TYPE VARCHAR(20);
ALTER TABLE "alokasi" ALTER COLUMN "roId" TYPE VARCHAR(20);